### ISSUE TITLE
keycloak not working on new docker deployment

### ISSUE THREAD

**Issue by danionescu2007** [H2-invent/jitsi-admin#323]
Installed a vanilla docker deployment to the letter, from the latest master.

The keycloak container fails with the log here: https://gist.github.com/danionescu2007/13c4c9c348eddedb2c7cbea82abf9b80
If I retry starting the container it only throws a message:
```
User with username 'admin' already added to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json'
```

and then exits.

Could you please help me debug this?
Thank you in advance.

**Comment by danionescu2007** [comment]
Thank you for your quick reaction 🥇

**Comment by holema** [comment]
Hello @danionescu2007,

thanks for your reporting.
I found the error and fixed it in the version 0.73.3

You need to reset the installation. Follow these steps
1. docker-compose down -v
2. git add .
4. git stash
5. bash installDocker.sh

**Comment by danionescu2007** [comment]
Thanks again.
Also I think I have to do a git pull to get the latest version from master.

**Comment by holema** [comment]
exactly. 
First checkput the latest master with `git pull`
And then my other steps afterwords.

```
git pull
docker-compose down -v
git add .
git stash
bash installDocker.sh
```

**Comment by holema** [comment]
Is it working now @danionescu2007

**Comment by danionescu2007** [comment]
I am afraid it does not. I even pruned the docker  volumes. No go. Started from scratch with git clone. Now it is building. I will keep you posted.

**Comment by danionescu2007** [comment]
It might not be able to connect to the database?

```
20:10:29,315 WARN  [org.jboss.jca.core.connectionmanager.pool.strategy.OnePool] (ServerService Thread Pool -- 60) IJ000604: Throwable while attempting to get a new connection: null: javax.resource.ResourceException: IJ031084: Unable to create connection
        at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:364)
        at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:371)
        at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:287)
        at org.jboss.ironjacamar.impl@1.5.3.Final//org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.createConnectionEventListener(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:1328)
        at org.jboss.ironjacamar.impl@1.5.3.Final//org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.getConnection(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:505)
        at org.jboss.ironjacamar.impl@1.5.3.Final//org.jboss.jca.core.connectionmanager.pool.AbstractPool.getSimpleConnection(AbstractPool.java:640)
        at org.jboss.ironjacamar.impl@1.5.3.Final//org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:605)
        at org.jboss.ironjacamar.impl@1.5.3.Final//org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:624)
        at org.jboss.ironjacamar.impl@1.5.3.Final//org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.getManagedConnection(TxConnectionManagerImpl.java:440)
        at org.jboss.ironjacamar.impl@1.5.3.Final//org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnection(AbstractConnectionManager.java:789)
        at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:151)
        at org.jboss.as.connector@26.0.1.Final//org.jboss.as.connector.subsystems.datasources.WildFlyDataSource.getConnection(WildFlyDataSource.java:64)
        at org.keycloak.keycloak-model-jpa@16.1.1//org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.getConnection(DefaultJpaConnectionProviderFactory.java:414)
        at org.keycloak.keycloak-model-jpa@16.1.1//org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lazyInit(LiquibaseDBLockProvider.java:65)
        at org.keycloak.keycloak-model-jpa@16.1.1//org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lambda$waitForLock$2(LiquibaseDBLockProvider.java:96)
        at org.keycloak.keycloak-server-spi-private@16.1.1//org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:753)
        at org.keycloak.keycloak-model-jpa@16.1.1//org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.waitForLock(LiquibaseDBLockProvider.java:94)
        at org.keycloak.keycloak-services@16.1.1//org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:134)
        at org.keycloak.keycloak-server-spi-private@16.1.1//org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:239)
        at org.keycloak.keycloak-services@16.1.1//org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:128)
        at org.keycloak.keycloak-wildfly-extensions@16.1.1//org.keycloak.provider.wildfly.WildflyPlatform.onStartup(WildflyPlatform.java:36)
        at org.keycloak.keycloak-services@16.1.1//org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:114)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ConstructorInjectorImpl.constructOutsideRequest(ConstructorInjectorImpl.java:225)
```

**Comment by holema** [comment]
What environment did you choose? prod or dev?

**Comment by danionescu2007** [comment]
There were my settings:

KEYCLOAK_PW=xrzluyvSmx8NZLAcEO7xdeJ9BOrCK5Dm
MERCURE_JWT_SECRET=REDACTED
KEYCLOAK_ADMIN_PW=REDACTED
NEW_UUID=REDACTED
JITSI_ADMIN_PW=REDACTED
ENVIRONMENT=prod
HTTP_METHOD=https
PUBLIC_URL=SOMEDOMAIN.com
smtpHost=smtp.gmail.com
smtpPort=587
smtpUsername=REDACTED
smtpPassword=REDACTED
smtpEncryption=tls
smtpFrom=noreply@verasidan.com

**Comment by danionescu2007** [comment]
Here is the full log:
[keycloak.log](https://github.com/H2-invent/jitsi-admin/files/9162564/keycloak.log)

**Comment by holema** [comment]
Thats realy strange. I just tested it with my docker and it worked fine.
I´m using docker version: Docker version 20.10.14, build a224086
and docker-compose version: Docker Compose version v2.4.1
is your database container running?

**Comment by danionescu2007** [comment]
Here I have `Docker version 20.10.17, build 100c701` with `Docker Compose version v2.6.1`

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/4688610/180308924-146fe848-2962-44aa-b1e5-5c7bb11d0338.png">

**Comment by danionescu2007** [comment]
This is the ending of the mariadb log:

```
2022-07-21 20:24:10+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.8.3+maria~jammy started.
2022-07-21 20:24:10+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2022-07-21 20:24:10+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.8.3+maria~jammy started.
2022-07-21 20:24:10+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
2022-07-21 20:24:10 0 [Note] mariadbd (server 10.8.3-MariaDB-1:10.8.3+maria~jammy) starting as process 1 ...
2022-07-21 20:24:11 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2022-07-21 20:24:11 0 [Note] InnoDB: Number of transaction pools: 1
2022-07-21 20:24:11 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2022-07-21 20:24:11 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
2022-07-21 20:24:11 0 [Warning] mariadbd: io_uring_queue_init() failed with ENOSYS: check seccomp filters, and the kernel version (newer than 5.1 required)
2022-07-21 20:24:11 0 [Warning] InnoDB: liburing disabled: falling back to innodb_use_native_aio=OFF
2022-07-21 20:24:11 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2022-07-21 20:24:11 0 [Note] InnoDB: Completed initialization of buffer pool
2022-07-21 20:24:11 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
2022-07-21 20:24:11 0 [Note] InnoDB: 128 rollback segments are active.
2022-07-21 20:24:11 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
2022-07-21 20:24:11 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
2022-07-21 20:24:11 0 [Note] InnoDB: log sequence number 46709; transaction id 14
2022-07-21 20:24:11 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2022-07-21 20:24:11 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-07-21 20:24:11 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
2022-07-21 20:24:11 0 [Note] Server socket created on IP: '0.0.0.0'.
2022-07-21 20:24:11 0 [Note] Server socket created on IP: '::'.
2022-07-21 20:24:11 0 [Note] InnoDB: Buffer pool(s) load completed at 220721 20:24:11
2022-07-21 20:24:11 0 [Note] mariadbd: ready for connections.
Version: '10.8.3-MariaDB-1:10.8.3+maria~jammy'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
```

**Comment by holema** [comment]
could you send me the file which is located in the keycloak directory. there must be a realm export.
You can send this file to entwicklung@h2-invnet.com, because there are some credentials in there.

end can you give me the docker inpect for the keycloak. That would be great

**Comment by holema** [comment]
And you can have a look in the docker-entrypoint-init-db directory. There must be a file with the secrets for the database. this passwords have to match with the password set in the docker inspect environments.

**Comment by danionescu2007** [comment]
Just checked it with https://jsonlint.com which reported `Valid JSON`:
[realm-export.json.txt](https://github.com/H2-invent/jitsi-admin/files/9162615/realm-export.json.txt)

It has been populated correctly by the sed commands:
[init-userdb.sql.txt](https://github.com/H2-invent/jitsi-admin/files/9162636/init-userdb.sql.txt)

**Comment by holema** [comment]
thanks. I downloaded it
can you add this line to the docker compse:
under service.keycloak.environment 
JDBC_PARAMS: "useSSL=false"

**Comment by danionescu2007** [comment]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/4688610/180310952-fc143308-169b-4b13-a19a-361f0d036532.png">

**Comment by holema** [comment]
exactly

**Comment by danionescu2007** [comment]
[keycloak.log](https://github.com/H2-invent/jitsi-admin/files/9162659/keycloak.log)

**Comment by holema** [comment]
i found the error. I will just create a hotfix. give me 5 minutes

**Comment by danionescu2007** [comment]
Take your time, I'm here 💯

**Comment by holema** [comment]
try 
```
git fetch
git add .
git stash
git checkout hotfix/keycloak_db_host
bash installDocker.sh
```

**Comment by holema** [comment]
you can delete the post with files you uploaded.

**Comment by danionescu2007** [comment]
[keycloak.log](https://github.com/H2-invent/jitsi-admin/files/9162723/keycloak.log)

**Comment by holema** [comment]
could you give me the docker inspect of the container. and there the environments

**Comment by danionescu2007** [comment]
[docker-inspect.txt](https://github.com/H2-invent/jitsi-admin/files/9162751/docker-inspect.txt)

**Comment by holema** [comment]
could you send me the database inspect. thats all realy strange, because the queus and the jitsi-admin could establish a connection.

**Comment by danionescu2007** [comment]
[docker-inspect-db-ja.txt](https://github.com/H2-invent/jitsi-admin/files/9162789/docker-inspect-db-ja.txt)

**Comment by danionescu2007** [comment]
Which linux flavor do you prefer for the host?
In the docs it was mentioned debian 10, so that's what I am using.

**Comment by holema** [comment]
![image](https://user-images.githubusercontent.com/22790152/180315789-2ee5cba5-f69b-4d29-8c96-7e58f1db09cb.png)
Thats the reason.
The DB-Host ist not the same as the db host in the keycloak env.
could you prune the complete docker and rebuild it.

I also use Debian10 or 11. Thats all fine

**Comment by danionescu2007** [comment]
```
docker-compose down -v
docker image prune
```
and then rebuild, right?

**Comment by holema** [comment]
```
docker-compose-down -v
docker system prune -a
git add .
git stash
bash installDocker.sh
```

**Comment by holema** [comment]
Is the error still there?

**Comment by danionescu2007** [comment]
yes

**Comment by holema** [comment]
is the hostname and the db_addr in the inpect now the same?

**Comment by danionescu2007** [comment]
checking

**Comment by danionescu2007** [comment]
<img width="372" alt="Screenshot 2022-07-22 at 00 41 25" src="https://user-images.githubusercontent.com/4688610/180320106-c4b1b4df-8dc4-4c46-8f9c-e8120e55132b.png">
<img width="302" alt="image" src="https://user-images.githubusercontent.com/4688610/180320192-ce6c2580-7fd5-4c27-88ea-4d784c72a44d.png">

**Comment by holema** [comment]
okay, so the first problem is solved :)
keycloak log ist still throwing the same error?

**Comment by danionescu2007** [comment]
retrying now with JDBC_PARAMS: "useSSL=false" added to keycloak.
Yes, still crashes and stops.

**Comment by holema** [comment]
do you have a ssh connection, so i can have a look on the server
thats so strange.

**Comment by danionescu2007** [comment]
sure, just a sec to set it up

**Comment by danionescu2007** [comment]
ssh://dan@5.12.94.101

pass: iqlevel@@HOME

su -
pass: ftw5r@@HOME

**Comment by holema** [comment]
thanks. i`m on the server

**Comment by danionescu2007** [comment]
right now is still building

**Comment by danionescu2007** [comment]
the source is checkout at root@webconference:~/docker/jitsi-admin#

**Comment by holema** [comment]
I found it already.
did it also take so long for becoming healty:

**Comment by danionescu2007** [comment]
yes it did

**Comment by holema** [comment]
normay it schould be finished after at least 40sec. so there it seems to be the first problem. I just take a look

**Comment by danionescu2007** [comment]
take you time 👍

**Comment by danionescu2007** [comment]
could `container_name: ...` help, in the db-ja section of the docker-compose?

**Comment by holema** [comment]
I try to rebuild it now with the same settings in the docker.conf I have in my environment

**Comment by holema** [comment]
> could `container_name: ...` help, in the db-ja section of the docker-compose?

normaly only the hostname is important to route through the internal network.

**Comment by danionescu2007** [comment]
roger that

**Comment by holema** [comment]
was it hanging also on step16 when you start the build?

**Comment by danionescu2007** [comment]
what's on step 16? some chmod or chown?

**Comment by holema** [comment]
yes it to one minute. I dont know why. normaly this takes only seconds.
I saw the server is huge. normaly it should deploy it in seconds.

**Comment by danionescu2007** [comment]
the storage is on HDDs not SSDs, maybe a bit slower because of that.

**Comment by holema** [comment]
I have a supposition. Perhaps it is, because the db is to late up. so the services want to connect, but the database is not fully up.

**Comment by danionescu2007** [comment]
Check this out: https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y/41854997#41854997

a helath check for the db-ja container would suffice.

**Comment by holema** [comment]
i try to build it in the docker conpose

**Comment by holema** [comment]
now it is not crashing. after waiting. the db server needs about 40secs in your configuration. this is quite long.

**Comment by danionescu2007** [comment]
👍 you added one more fail-safe to the project to make it fail-proof :)

**Comment by holema** [comment]
The keycloak is now building the database. but it is so slow. i think here we have to wait until tomorrow :)

**Comment by holema** [comment]
> 👍 you added one more fail-safe to the project to make it fail-proof :)

Indeed :)

**Comment by danionescu2007** [comment]
sure, thank you so much for everything

**Comment by danionescu2007** [comment]
it timed out. I will try on a ssd config.

**Comment by holema** [comment]
but now the keycloak is runing in a timeout, because the databse is to slow

**Comment by holema** [comment]
the keycloak realy writes a lot at the beginning.

**Comment by danionescu2007** [comment]
can I make it wait longer?

**Comment by holema** [comment]
I will make the hotfix tomorrow and then we can have an other look. 
try adding this to the env: JAVA_OPTS_APPEND="-Djboss.as.management.blocking.timeout=7200"
propably this will incrase the timeout

**Comment by holema** [comment]
the env of the service.keycloak

**Comment by danionescu2007** [comment]
got it. thanks. until tomorrow. good night.

**Comment by holema** [comment]
good night. not wondering, i add a new docker.conf, but i will replace it tomorrow :)

**Comment by holema** [comment]
I just pushed the small changes with the healthcheck so an git pull will get the latest changes.

**Comment by holema** [comment]
Thanks for the great feedback. We do our best.  Have you stared the repo already ;)

**Comment by danionescu2007** [comment]
Indeed. Much appreciated. Now heading to the next challenge: deploying Jitsi Meet via docker. :)

**Comment by holema** [comment]
Oh yes, this is a realy big challenge. But you will do it :)
